# Generated by Django 2.1.15 on 2020-03-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500, blank=False, default='')),
                ('month', models.DateTimeField()),
                ('headcount', models.FloatField()),
            ],
        ),
    ]
